spring:
  datasource:
    url: jdbc:mysql://spinxodb.c6ylyk9lhaqa.ap-south-1.rds.amazonaws.com:3306/consuldb
    username: spinxo
    password: 123456789
    driver-class-name: com.mysql.jdbc.Driver
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        id:
          new_generator_mappings: false
          
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 36000
      
UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
  
server:
  port: 1111